### ISSUE TITLE
Ants' path doesn't work on the cell phone

### ISSUE THREAD

**Issue by emirdeliz** [rubenspgcavalcante/leaflet-ant-path#108]
**Type:**
- [x] bug

**Environment:**
 - OS: 12.4.1
 - Browser: Safari
 - Library Version: 1.3.0

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**

Ants' path doesn't work on the cell phone. I tried to use it on safari and I'm unsuccessful.

**Comment by rubenspgcavalcante** [comment]
Hi @emirdeliz , sorry for the delay.
Which version is your safari mobile? Safari doesn't fully support SVG animations, so this is the big problem :(

**Comment by emirdeliz** [comment]
I don't know if there's anything that can be done then. I have the latest version of safari @rubenspgcavalcante

**Comment by rubenspgcavalcante** [comment]
13.1 right? Yep, it's complicated for me to test, don't have any device for debugging :/
I'll be closing for now
