### ISSUE TITLE
Polyline Manipulation Support

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [rubenspgcavalcante/leaflet-ant-path#11]
I use polylines on my map with realtime start and endpoint moving animated through jQuery easings, this just works fine and i like the antpath for styling, however, as it extends from FeatureGroup, it does not allow modifications like the polyline to (getLatLngs, setLatLngs, latLngSplice).

I see this plugin internally draws two polylines. I could wrap the required polyline methods and apply the changes to all internal polylines. Is this a good approach or do you have a better idea?

Chris

**Comment by rubenspgcavalcante** [comment]
Hello Chris!
Well, I think this is the better approach, implement the Polyline API and just proxy the call over the two internals polylines. Initially the AntPath was implemented just like the [MultiPolyline](http://leafletjs.com/reference.html#multipolyline), extending from FeatureGroup, but use a interface of a Polyline(single) makes more sense.

**Comment by chris-247-sloan** [comment]
Hi, Did this proposed enhancment ever get developed? 
I really like the way ant-path animates but need to be able to interact with the line also. 

Thanks.

**Comment by rubenspgcavalcante** [comment]
Hello Chris,
Yes I've already implemented the all the Polyline interface. But stills on the dev branch, because I'm doing some use case tests and also unitary tests. After that, I'll release a new version with this improvement.

Thanks for the interest

**Comment by chris-247-sloan** [comment]
Fantastic, Let me know if there is anything I can do to help. I'd be glad to.

**Comment by rubenspgcavalcante** [comment]
Do the jasmine tests for the polyline method would be a great help! 👍

**Comment by rubenspgcavalcante** [comment]
Released in the version v0.4.0 :smile:
