### ISSUE TITLE
Cannot set property 'MultiAntPath' of undefined

### ISSUE THREAD

**Issue by geekplux** [rubenspgcavalcante/leaflet-ant-path#15]
my leaflet version is 1.0.0-rc.1, and it dropped the `MultiAntPath` API.

<img width="503" alt="screen shot 2016-08-02 at 18 15 28" src="https://cloud.githubusercontent.com/assets/3816105/17325248/312b1f8e-58dd-11e6-9232-c324e4b91bd2.png">

**Comment by rubenspgcavalcante** [comment]
Currently leaflet version 1.x is not supported (#5) , but in some days I'll release a version supporting it.
