### ISSUE TITLE
Is there a way to modify the options after instantiating? (e.g. opacity, dashArray, etc...)

### ISSUE THREAD

**Issue by nemosmithasf** [rubenspgcavalcante/leaflet-ant-path#157]
**Solution for posterity**
Use the `.setStyle` method

---
**Original**
I tried changing the `options` object, but there was no change reflected.

Given the demo on the homepage, I assume it must be possible (https://rubenspgcavalcante.github.io/leaflet-ant-path/)

**Comment by PopCandier** [comment]
ty
