### ISSUE TITLE
Possible to Apply this to Polygon Borders?

### ISSUE THREAD

**Issue by tdaubs** [rubenspgcavalcante/leaflet-ant-path#16]
Really like this extension! It would be great to see this functionality applied to the borders of a polygon. Not sure if that is a ton of work (it probably is...) but it would be very useful to highlight a specific area.

**Comment by rubenspgcavalcante** [comment]
Thanks! I'll check the behavior with the current implementation :+1:

**Comment by rubenspgcavalcante** [comment]
Sorry for the late response. Probably this feature will escape the intend of the plugin, so if you want to fork the repository and modify it to work in polygons, you're welcome! :)
