### ISSUE TITLE
Continuar longitude mapa seguinte

### ISSUE THREAD

**Issue by rohling** [rubenspgcavalcante/leaflet-ant-path#17]
Olá Rubens, parabéns pelo seu trabalho.
É possível com seu plugin continuar escrevendo a linha da longitude no mapa ao lado? Exemplo, tenho  [54, -50], [60, 150], [70, -10]... quando chega no -10 retorna e desenha no mapa atual. Gostaria de continuar no mapa seguinte(ou em todos), como este exemplo com a linha amarela da órbita, http://www.n2yo.com/?s=28057

Obrigado,

**Comment by rubenspgcavalcante** [comment]
Obrigado Adair!
Bom, minha biblioteca tem as mesmas regras e API dos objetos [L.Polyline](http://leafletjs.com/reference.html#polyline). Nunca cheguei a testar esse caso, mas se o Polyline der suporte, o AntPath também dará. Dá uma olhadinha na API do Leaflet sobre esse caso :)

**Comment by rubenspgcavalcante** [comment]
Teste esse parâmetro na inicialização do mapa:
`'worldCopyJump': true`

http://stackoverflow.com/questions/28320928/how-to-replicate-marker-position-on-map-loop-leaflet-js
