### ISSUE TITLE
How to use it on iPython

### ISSUE THREAD

**Issue by existeundelta** [rubenspgcavalcante/leaflet-ant-path#19]
Would be great having an iPython "hello world" 
thanks

**Comment by rubenspgcavalcante** [comment]
Are you meaning a iPython notebook (.ipynb), from the Jupyter project?
If you want a sample, I'm currently creating a dev. environment with samples of use. Also you can see the gh-pages branch for the source of the example provided in the README file.

**Comment by existeundelta** [comment]
thanks i will take a look, are them using folium?

**Comment by rubenspgcavalcante** [comment]
The AntPath is injected in the L.Polygon namespace. If folium have access to it, you can use normally.
