### ISSUE TITLE
Remove 'dist' files from repo

### ISSUE THREAD

**Issue by IvanSanchez** [rubenspgcavalcante/leaflet-ant-path#2]
Implement the well-known convention of not keeping built/compiled files in a version control system (git repo), automate builds of the code when users pull the project via `npm install`.

Also make sure that `package.json` has the right dependencies for automatically building when installing, and the built filepaths match the `main` section of `package.json`.

**Comment by rubenspgcavalcante** [comment]
Restructured and removed dist files
875e9106e4019b8f94ad570548bfe6dde9d31c04
