### ISSUE TITLE
Path dashArray is expected to be a string (Leaflet 1.0.2)

### ISSUE THREAD

**Issue by ebrensi** [rubenspgcavalcante/leaflet-ant-path#25]
The leaflet documentation specifies that `dashArray` is a string (eg "5,10"), but leaflet-ant-path uses an  array (eg.  [5,10] ).  
http://leafletjs.com/reference-1.0.2.html#path-dasharray

Using an array works in leaflet with the default (SVG) renderer but canvas renderer [Canvas.js](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js) `_updateDashArray` throws an error when it tries to split the string.  Animation doesn't work with Canvas renderer yet but it might in the future so we should make sure the settings are consistent.

**Comment by rubenspgcavalcante** [comment]
Now you can also use string in the dashArray on the v0.5.0.
I'll close for now, but if it continue breaking, you can open it again.
