### ISSUE TITLE
Use with bringToBack()

### ISSUE THREAD

**Issue by jcoupey** [rubenspgcavalcante/leaflet-ant-path#26]
Hi, I would like to have a regular polyline and an antPath on the same overlay. The antPath has to be added later and should be "behind" the polyline. Here is a minimal example of what I'm trying to achieve.

```javascript
var L = require('leaflet');
var antPath = require('leaflet-ant-path').AntPath;

var map = L.map('map').setView([48.8245,2.4355], 11);

var points_1 = [[48.87013489622034,2.305755615234375],[48.89180956320587,2.338714599609375],[48.87555444355432,2.379913330078125],[48.850258199721495,2.399139404296875],[48.829469576885984,2.3345947265625],[48.81048112472012,2.418365478515625],[48.8737479930069,2.4334716796875]];

var points_2 = [[48.86855408432749,2.4066925048828125],[48.88007028454358,2.3713302612304688],[48.862682060035624,2.38128662109375],[48.87758662245016,2.3191452026367188],[48.8473212003792,2.3263549804687496],[48.827661462789415,2.2528839111328125]];

var p1 = L.polyline(points_1, {color: 'red', weight: 2});

var p2 = L.polyline.antPath(points_2, {color: 'blue',
                                       opacity: 0.8,
                                       weight: 5,
                                       delay: 400,
                                       dashArray: "10, 20",
                                       pulseColor: '#FFFFFF'});

var myGroup = L.featureGroup([p1]).addTo(map);

myGroup.addLayer(p2);

// p2.bringToBack();
```
So far so good, the animation is working fine but the antPath is above the polyline, and as soon as I uncomment that last line, the antPath is behind all right but looses the animation.

I'm using leaflet 1.0.3 and leaflet-ant-path 0.5.0 with Firefox 52.0.1

**Comment by rubenspgcavalcante** [comment]
Hi @jcoupey, I'll check it. Thanks for providing the code 👍

**Comment by rubenspgcavalcante** [comment]
So, I've made the corrections on the implementation of bringToBack and bringToFront to consider the order of the static and animated polylines from AntPath and now is working 🎉

<img width="655" alt="screen shot 2017-03-31 at 17 26 26" src="https://cloud.githubusercontent.com/assets/739913/24557214/36915e30-1637-11e7-858e-1ff8a65cd193.png">

 I'll release a patch version for this :)

**Comment by jcoupey** [comment]
Wow, that was a fast fix, thanks! ;-)

I'll be happy to provide feedback after checking out your patch once it's published.

**Comment by rubenspgcavalcante** [comment]
You're welcome! Thanks again for provide the code, this makes the things much easier! 👍 
The version 0.5.1 is already on npm, now I'll update bower :)

**Comment by jcoupey** [comment]
Just letting you know everything works as expected now with my code. Thanks again for fixing and publishing! :+1:

**Comment by lin559** [comment]
Hi @jcoupey I use the same code,but it didn't work , the red line still behind the antPath.
```
                import {AntPath, antPath } from "leaflet-ant-path";
		var points_1 = [[48.87013489622034,2.305755615234375],[48.89180956320587,2.338714599609375],[48.87555444355432,2.379913330078125],[48.850258199721495,2.399139404296875],[48.829469576885984,2.3345947265625],[48.81048112472012,2.418365478515625],[48.8737479930069,2.4334716796875]];

		var points_2 = [[48.86855408432749,2.4066925048828125],[48.88007028454358,2.3713302612304688],[48.862682060035624,2.38128662109375],[48.87758662245016,2.3191452026367188],[48.8473212003792,2.3263549804687496],[48.827661462789415,2.2528839111328125]];

		var p1 = L.polyline(points_1, {color: 'red', weight: 2});

		var p2 = L.polyline.antPath(points_2, {color: 'blue',
		                                       opacity: 0.8,
		                                       weight: 5,
		                                       delay: 400,
		                                       dashArray: "10, 20",
		                                       pulseColor: '#FFFFFF'});

		var myGroup = L.featureGroup([p1]).addTo(this.map);

		myGroup.addLayer(p2);
		p2.bringToBack();
```
the version detail is:     "leaflet": "^1.3.4",
    "leaflet-ant-path": "^1.1.2"

**Comment by jcoupey** [comment]
@lin559 I'm getting the same behaviour using 1.1.2 with leaflet 1.3.4. It looks like `bringToBack` does not work any more, which is not the same as the initial issue above.

@rubenspgcavalcante do you think this might be due to changes in leaflet?

**Comment by rubenspgcavalcante** [comment]
It may be 🤔 
I need to check it further tho
I'll reopen while I'm getting more info about this 👍

**Comment by rubenspgcavalcante** [comment]
Checking here, it seems to be a problem on leaflet itself.
It's treating both features as not related, setting the z-index of them to 200.
When calling bringToFront or bringToBack both stay with the same 200 z-index, even if one feature group is inside the other.

I'll try to reproduce better and open a issue on Leaflet itself

**Comment by jcoupey** [comment]
Thanks for investigating! I'll keep an eye to know when I can upgrade leaflet-ant-path.

For what it's worth, I've been able to move to Leaflet 1.3.4 while keeping leaflet-ant-path at 0.5.0 and `bringToBack` still works as expected for me.

**Comment by rubensolx** [comment]
Interesting, thanks for the info!
I'll what I can do on my side too

**Comment by rubenspgcavalcante** [comment]
Interesting, thanks for the info!
I'll what I can do on my side too
