### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fffvow** [rubenspgcavalcante/leaflet-ant-path#34]
hi,I'm not good at english and i'm a chinese new  js coder,but this plugin is amazing.i think must use it, so i think i need some help from you.   The thing is i'm not good at nodejs and webpack,and when i install them,there are lots of error i'm closing crazy...,so i just want some  js files for script tag in html and some APIs... no npm no webpack... so do you have some js files for me? 
i kown this is too much but i really need this, so could you help me? thank you very much

**Comment by fffvow** [comment]
i found files , thank you ,this plugin is amazing!

**Comment by rubenspgcavalcante** [comment]
No problem with the english @fffvow , I'm also not so good at it :P
Thanks for using the plugin, and you're welcome :)

**Comment by fffvow** [comment]
oh you can understand what i said! i'm so exceting , yeah,I'm not good at Chinese too,haha,..by the way,you are the first man that i talk with who is a foreign ( this word is find by a dictionary ) people
