### ISSUE TITLE
Can't clear/remove antPath layer from featureGroup

### ISSUE THREAD

**Issue by movihus** [rubenspgcavalcante/leaflet-ant-path#37]
When I added ant-path to a featuregroup and try to remove the layer from map by using featuregroup.clearLayers() or antpath.remove() the polyline is not removed. Even when I using layer control plugin and hide the layer where ant-path is contained is not removed.

An example here: https://jsfiddle.net/4o3bvjg8/

Please help.

**Comment by rubenspgcavalcante** [comment]
I see, I will set this issue as bug 👍

**Comment by rubenspgcavalcante** [comment]
Fix published in the patch version v0.6.4 👍
