### ISSUE TITLE
Add code snippets to the demo page

### ISSUE THREAD

**Issue by ivleth** [rubenspgcavalcante/leaflet-ant-path#39]
Hi, is it possible to add a simple html example page like the other leaflet plugins do? I am batteling with which javascript and css files I need to use. They all seem to be nested and referenced to each other. Also, the leaflet-ant-path-master\dev-env\index.html page doesn't seem to work.

Plugin is looking great, love to use it. Thanks

**Comment by rubenspgcavalcante** [comment]
Hi ivleth,
I'll add some code snippets to the [demo page](https://rubenspgcavalcante.github.io/leaflet-ant-path/)

**Comment by ivleth** [comment]
that is highly appreciated!! waiting for it :-)

**Comment by rubenspgcavalcante** [comment]
New site released with code snippets + docs 🎉 
https://rubenspgcavalcante.github.io/leaflet-ant-path/
