### ISSUE TITLE
Warn about incompatibility if map option "preferCanvas" is set "true"

### ISSUE THREAD

**Issue by TurnkeyTyranny** [rubenspgcavalcante/leaflet-ant-path#41]
Problem : No animation if leaflet map preferCanvas option is set to true
cause : the element doesn't have the ant-path-xxxxx class applied
fix: don't use preferCanvas from the leaflet library

**Comment by rubenspgcavalcante** [comment]
Hi @TurnkeyTyranny ,
That's true, as the plugin works using CSS transitions over the SVG, it will not work inside canvas, as there's now way to get the information about the elements drawn inside of it.
I'll update the README file warning about this.
