### ISSUE TITLE
delay didn't work at initial mount

### ISSUE THREAD

**Issue by ctxhou** [rubenspgcavalcante/leaflet-ant-path#44]
**Type:**
- [x] bug  
- [ ] feature
- [ ] enhancement
- [ ] question
 
**Environment:**
 - OS: Windows N/A
 - Version: 0.6.X
 
**Going to open a PR:**
- [ ] yes
- [x] no
 
**Description:**  
Hi,

I'm using factory way to write antPath. With previous version `0.4.X`, the delay option work well. 
But when I upgrade to `0.6.X`, delay didn't work at initial mount. It worked after render again.

It seems like a bug.

```javascript
const antPolyline = L.polyline.antPath(latlngs, {delay : 1000});
```

Does anyone have this problem?

**Comment by rubenspgcavalcante** [comment]
Hi @ctxhou , currently I'm without my personal computer, but I'm going to check this one 👍

**Comment by rubenspgcavalcante** [comment]
Hello @ctxhou , can you say which browser this happens. I've made some tests locally and in codepen, and the delay is working fine.

**Comment by rubenspgcavalcante** [comment]
Closing by inactivity
