### ISSUE TITLE
"Reflect" cause problems with Internet Explorer

### ISSUE THREAD

**Issue by maxdeepfield** [rubenspgcavalcante/leaflet-ant-path#46]
**Type:**
- [x] bug  
- [ ] feature
- [ ] enhancement
- [ ] question
 
**Environment:**
 - OS: Windows
 - Version: N/A
 
**Going to open a PR:**
- [ ] yes
- [x] no
 
**Description:**  
**IE11** says that 'Reflect' is undefined and this causes fatal stop of running script.
as I know Reflect is not supported in IE
can there be workarounds?

**Comment by rubenspgcavalcante** [comment]
Currently I have no windows machine, but I know Microsoft provides an image of Windows 7 I think, for developers who want to do tests over Internet Explorer.
Much probably the pollyfill isn't working as should. I'll check core-js Reflection polyfill support for more information. I'll try to reserve some time on this. 👍

**Comment by tmh12345** [comment]
@rubenspgcavalcante 
Yes. I have added core-js and there is no more error appear. But the only problem is the path no being animated as below:
![image](https://user-images.githubusercontent.com/39986306/50589077-090f0600-0ec0-11e9-94fe-a85f3c5c0616.png)

**Comment by tmh12345** [comment]
@rubenspgcavalcante yaya

**Comment by rubenspgcavalcante** [comment]
Closing this one because of the incompatibility with any version of IE.
See #71 and #72
