### ISSUE TITLE
Change Direction

### ISSUE THREAD

**Issue by hellracer** [rubenspgcavalcante/leaflet-ant-path#47]
Hi,

Before anything else thanks for the plugin, I would like to ask is it possible to change the direction of the animation?, I haven't see in the example that allows me to do this, thanks in advance

**Comment by hellracer** [comment]
Sorry, please disregard this I just think read the documentation fully using runtime-generator, we can do this! 👍

**Comment by rubenspgcavalcante** [comment]
Ok, no worries!
In any case you're can always create a reverse animation just by reversing the direction of the latLngs:
```js
const reverseAntPath = antPath(path.reverse())
```

AntPath will always respect the order in your latLng path array 👍

**Comment by bthieurmel** [comment]
Hi,

Is it possible to update direction without redrawing the entire polylines ? (just updating this propertie, and so the animation, like when we update color for example...).

Can be very very usefull in my specific case...!

Thanks.

**Comment by rubenspgcavalcante** [comment]
Hi @bthieurmel , for big paths this really makes sense. Should be more performatic doing this inversion directly on the animation (with no redraws).

I'll open an new issue, and work on this 👍

**Comment by rubenspgcavalcante** [comment]
https://github.com/rubenspgcavalcante/leaflet-ant-path/issues/49
