### ISSUE TITLE
"core " global variable is a too generic name

### ISSUE THREAD

**Issue by JosephIsrael-dooblegroup** [rubenspgcavalcante/leaflet-ant-path#48]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: All
 - Browser: All
 - Library Version: 0.6.4

**I'm going to open a PR:**
- [ ] yes
- [ ] no

**Description:**
The component set "core" as a global variable override my app core global variable, it could be better to not use such a generic variable name

**Comment by rubenspgcavalcante** [comment]
Hi @JosephIsrael-dooblegroup ,
This isn't exported by ant-path, but by core-js. Any library that you use which have core-js as dependency will have the same effect. You can open an issue in their [repo](https://github.com/zloirock/core-js).
