### ISSUE TITLE
Reverse animation method/option

### ISSUE THREAD

**Issue by rubenspgcavalcante** [rubenspgcavalcante/leaflet-ant-path#49]
**Type:**
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] question

**Environment:**
 - OS: All
 - Browser: All

**I'm going to open a PR:**
- [x] yes
- [ ] no

**Description:**
Create a reverse-animation method and option to change the animation direction without redrawing the element in the map.

**Comment by bthieurmel** [comment]
Great! Sorry for this question but can you estimate the delay of implementation of this new features ?

Many thanks.
