### ISSUE TITLE
Test on Leaflet 1.0.0

### ISSUE THREAD

**Issue by IvanSanchez** [rubenspgcavalcante/leaflet-ant-path#5]
Leaflet 0.7.x will (hopefully) be deprecated soon. Check compatibility with Leaflet 1.0.0 and optionally provide different flavours of the plugin for 0.7.x and 1.0.0.

**Comment by rubenspgcavalcante** [comment]
Now supporting leaflet v1.x (362d5ad72ad83dc5666c93bb267e7982c5dbc0e2)
