### ISSUE TITLE
AntPath doesn't animate

### ISSUE THREAD

**Issue by rankerz** [rubenspgcavalcante/leaflet-ant-path#52]
Hi,

I'm new on AntPath, I find it really great and I want to thank you for it.
I'm not a high level Leaflet Developper, but I have a problem to animate the AntPath. 

Here is a simple test I made to check if it works before coding my whole script :
`<script type="text/javascript" src="assets/js/leaflet.v2.js"></script>
<script type="text/javascript" src="assets/js/leaflet-ant-path.js"></script>

var map = L.map('mapid').setView([[48.837953,2.495499], [48.831214,2.493777]],15);

var antPolyline = new L.polyline.antPath([[48.837953,2.495499], [48.831214,2.493777]],{"delay":100,"dashArray":[5,10],"weight":5,"color":"#ff0000","pulseColor":"#FFFFFF","paused":false,"reverse":true}).addTo(map);
`

With this code, the AntPath is correctly printed, but there is no animation.
Is there something wrong ? 

Thanks !

**Comment by Aditya-Sh** [comment]
I had similar issue, in my case i had `preferCanvas` option for map set to true. Setting it false or removing it should work for you. I don't know if this is a bug or desired behaviour.

**Comment by rubenspgcavalcante** [comment]
In the docs there's a warning about this added on (#42).
I'll create a warning on the console too, to make this more clear.

**Comment by Aditya-Sh** [comment]
I was wondering if we could have arrow denoting direction of animation, I checked the source, so I understood you are using stroke property `stroke-linecap`. If we could add an option to provide an custom svg?

**Comment by rubenspgcavalcante** [comment]
Css animations don't work in canvas. The way to do is much probably doing by JS, and changing the object properties directly. One thing I'm afraid is how much this will affect the performance, because even id canvas is much more faster, doing this by JS can be rendering blocker. :(

I'll try to do some tests in the code and run some audits on it to see if is viable tho :)

**Comment by Aditya-Sh** [comment]
I tried but then was stuck in something else so forgot about this. I'll check if there's a way we could do this. Thanks.

**Comment by rubenspgcavalcante** [comment]
Opened a new issue for that #54

**Comment by rankerz** [comment]
Hi, thanks for your replies !

So, I initialized the new map by that way : 

var map = L.map('mapid',{center:[43.370071,3.273687], zoom: 14, preferCanvas:false});

but it doesn't work. Did you mean to set preferCanvas that way ? Because I have the same problem, it doesn't animate !
Thanks ! :)

**Comment by Aditya-Sh** [comment]
Yes, this should work, can you add more points to your antPath and check or create jsfiddle link if possible with your config.

**Comment by rankerz** [comment]
That's ok it works for me now, I missed something in the map declaration !

Thanks for your help !

**Comment by anujkamat29** [comment]
I have implemented the same code and it works on almost all the browsers(Chrome, Edge, Firefox) but not on IE. Please help.

**Comment by Luffy-D-Monkey** [comment]
> That's ok it works for me now, I missed something in the map declaration !
> 
> Thanks for your help !

Hi harmondale, I meet with the same problem using npm, it can draw the static ant path on the map instead of animation ant path. I also  tried to use antpath.resume() to redraw it, but it keep return false and doesn't work.

What's your solution?
