### ISSUE TITLE
is there a leaflet.antpath.js file that vanilla JS folks like me can use?

### ISSUE THREAD

**Issue by answerquest** [rubenspgcavalcante/leaflet-ant-path#53]
**Type:**
- [x] question

**Environment:**
 - OS: Ubuntu 16.04
 - Browser: Chromium (similar to chrome) 
 - Library Version: v1.0.1

**I'm going to open a PR:**
- [x] no

**Description:**
Hi, apologies but I'm from the vanilla JS days, and the place where I want to publish my map with your awesome plugin animating the line, is also not going to have npm etc installed. Is there a .js file that I can include in my HTML, like `<script src="leaflet.antpath.js" type="text/javascript"></script>` to make this work? I looked up your demo's source code but it befuddles me. I've been using leaflet and several other plugins too since a long time and there's a clear .js file to use in the other cases. 

If there is one, could you put a mention of it in the readme?
Great work btw.

**Comment by rubenspgcavalcante** [comment]
If you check the docs, you can use directly from the CDN:
`<script src="https://unpkg.com/leaflet-ant-path" type="text/javascript"></script>`
Or just download the file [here](https://github.com/rubenspgcavalcante/leaflet-ant-path-bower/archive/master.zip)
