### ISSUE TITLE
Reverse animation behaves incorrectly

### ISSUE THREAD

**Issue by ivany4** [rubenspgcavalcante/leaflet-ant-path#58]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: Any
 - Browser: Any

**I'm going to open a PR:**
- [x] yes
- [ ] no

**Description:**
Initially reversed path has a [class](https://github.com/rubenspgcavalcante/leaflet-ant-path/blob/00dc278addc1f81fb3a3e69e4202922a686b22ad/src/plugin/components/ant-path.component.js#L81) `leaflet-ant-path__reverse`, while toggling the reverse [tries to operate](https://github.com/rubenspgcavalcante/leaflet-ant-path/blob/00dc278addc1f81fb3a3e69e4202922a686b22ad/src/plugin/components/ant-path.component.js#L129) class `reverse`, which does not exist. `reverse` does not affect animation, since sass is configured for `leaflet-ant-path__reverse` too.

**Comment by rubenspgcavalcante** [comment]
Will release a patch version now 👍
