### ISSUE TITLE
Curved Ant-Path

### ISSUE THREAD

**Issue by sebastienpattyn93** [rubenspgcavalcante/leaflet-ant-path#64]
**Type:**
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: Ubuntu 18.04 LTS
 - Browser: Firefox Quantum 61.0.1
 - Library Version: 1.1.2

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
Is it possible to create curved ant-paths? If not, this would be a nice feature, I tried to integrate it Ant-Path with Leaflet.Curve but never got the result I would like to have.

**Comment by rubenspgcavalcante** [comment]
Released a new version (1.2.0) with support to custom vectors :)
