### ISSUE TITLE
Adding browser compatibility to the docs

### ISSUE THREAD

**Issue by rubenspgcavalcante** [rubenspgcavalcante/leaflet-ant-path#72]
**Type:**
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] question

**Environment:**
 - OS:
 - Browser:
 - Library Version:

**I'm going to open a PR:**
- [x] yes
- [ ] no

**Description:**
As discussed on #71 , some old browsers like IE11- and some Edge builds don't support CSS filter/animations on SVGs.
The idea is add this section on the docs to warn the users of the plugin, together with some information about how many users can be affected with data from https://caniuse.com

**Comment by tmh12345** [comment]
@rubenspgcavalcante Thank you very much for your kindly helping. Appreciate it a lot.
