### ISSUE TITLE
Pattern is re-adjusted when one moves the map

### ISSUE THREAD

**Issue by braandl** [rubenspgcavalcante/leaflet-ant-path#8]
When the map is moved, so that not the entire path is seen on it, the pattern gets readjusted.
This has weird effects on the animation when moving the map around, or having an automated movement animation bound to the map.

I just found out, that it is dependend with the clipping of line segments.
Adding noClip: true fixes this, even though it seems dirty.

**Comment by rubenspgcavalcante** [comment]
Well, as you said, this is a normal behavior on a polyline. I'll not force the no clipping, but I can set it as default 'true'. So, if the developer really wants to use the no clip property (probably because peformance), he can do it by passing noclip as 'false'.
