### ISSUE TITLE
Ant animation appears on paths that are set to paused if there is at least one path with animation next to it.

### ISSUE THREAD

**Issue by ckotyan** [rubenspgcavalcante/leaflet-ant-path#86]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: Mac
 - Browser: Chrome
 - Library Version: 1.2.1

**I'm going to open a PR:**
- [ ] yes
- [ ] no

**Description:**
[ Ant animation appears on paths that are set to paused if there is at least one adjacent path with animation next to it.]
Is there a way to ensure paused animation paths do not display the dash lines at all?

**Comment by ckotyan** [comment]
I would love to fix it If I knew what is going on and submit the PR

**Comment by samanabo** [comment]
I took a quick look at this, it seems the method to generate the path IDs could result in two paths having the same ID. This is because the current date/time is used for the ID, and paths can be created within the same millisecond.

**Comment by samanabo** [comment]
@rubenspgcavalcante have you had a chance to look this over? I think this is still an issue... thanks!

**Comment by moritz4** [comment]
I'm also having this problem when creating multiple paths in a loop. Because they are created so quickly after one another, they have the same animatedPathId. When I pause() or resume() one of them, it effects them all.
